name: Linux (GCC)

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        build-type: [Debug, Release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Clone repo

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v2
      with:
        path: ~/.cache/vcpkg
        key: ${{ runner.os }}-${{ hashFiles('~/.cache/vcpkg') }}

    - name: vcpkg testing
      run: |
        vcpkg install sdl2
        tree ~/.cache/vcpkg

    - name: Generate build files 
      # The -DCMAKE_BUILD_TYPE variable only matters to single-config generators
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Build project
      run: cmake --build ${{ github.workspace }}/build

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      # Run the tests
      run: ctest -C --output-on-failure
