name: Windows (MSVC)

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        build-type: [Debug, Release]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2 # Clone repo

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v2
      with:
        path: C:/Users/runneradmin/AppData/Local/vcpkg
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: ${{ runner.os }}-vcpkg-

    - name: Install Dependencies with vcpkg
      run: vcpkg install

    - name: Generate build files 
      run: cmake -B ${{github.workspace}}/build

    - name: Build project
      # The --config option is only used on multi-config generators
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }} --parallel 2

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      # Run the tests, selecting the configuration
      run: ctest -C ${{ matrix.build-type }} --output-on-failure
